### PR TITLE
Adding new option in Pie chart to show label inside Arc

### PR DESCRIPTION
**Pull request by sonuks**
There is a new option to show the Legend - Inside Arc

1. PieChartLabel.cs - Line 332 - Added new Enum - DisplayMode.InsideArc
2. PieChartLabel.cs -Line 133 - Updated existing method - PositionLabel()
3. PieChartLabel.cs -Line 156 - Added new method  - PositionInsideArc()
4. DataVisualisationSample.xaml - Modified the demo 
5. global.json - updated SDK version to 3.1.300

image

### CODE REVIEW

**Comment by jogibear9988** [comment]
@sonuks why did you close the pull?

**Comment by jogibear9988** [comment]
should I not merge it?

**Comment by sonuks** [comment]
Raising new pull request

**Comment by sonuks** [comment]
Please merge the changes

**Comment by jogibear9988** [comment]
thanks

**Pull request merged**
