### PR TITLE
Added watermark to AutoCompleteBox

### PR DESCRIPTION
**Pull request by diab0l**

### CODE REVIEW

**Comment by micdenny** [comment]
@diab0l thanks for the PR!

@jogibear9988 I saw there's an AppVeyor connected to this repo, and that's failing, if you add me also as an appveyor member of wpftoolkit project, I can give a look at. The error anyway seems to be easy to fix:

> Specify which project or solution file to use because the folder contains more than one project or solution file.

**Comment by diab0l** [comment]
@micdenny You're welcome, I hope the changes I made are in line with the project.

That's a sensible error message, since the repo does contain three solutions. I wonder how the upstream version passes the build :3

**Comment by jogibear9988** [comment]
sorry, don't know how to add a user to appveyor... I also wanted to setup appveyor so it pushes the nuget package... I will look for this next week!

**Comment by micdenny** [comment]
> sorry, don't know how to add a user to appveyor

I think from [your team section](https://ci.appveyor.com/team) and you can directly add [GitHub teams](https://ci.appveyor.com/gitHubTeams) selecting `dotnetprojects/wpftoolkit` and providing Administrator role, and that's it I think, never tried :smile:

**Comment by jogibear9988** [comment]
Added....

**Comment by jogibear9988** [comment]
Will the Watermark also Hide when some Text is Entered? Because I don't see when ShowWaterMark changes!
And would it not be easier if we replace the TextBox with a WatermarkedTextBox?

**Comment by micdenny** [comment]
@jogibear9988 mmm... I think I'm seeing too much stuff in AppVeyor, I'm a co-administrator of YOU :smile: actually I don't think is what I meant to let you do, but don't worry I'll not missed up anything...  probably we will need to create a separated project account? actually dunno, we'll take time to figure out this, maybe in another issue, actually I need to figure it out for another couple of projects, so I will update you as soon as I understand what to do.

**Comment by micdenny** [comment]
now the build works, and this is the badge:

[Build status](https://ci.appveyor.com/project/jogibear9988/wpftoolkit)

**Comment by jogibear9988** [comment]
Whats with this Ticket? Should it be merged, or should there changes be done?

**Comment by diab0l** [comment]
Well, as it is, it is completely driven from outside.
I do admit that with a TextBoxStyle and template the same could be done, but then the binding gets rather clumsy.

Currently ShowWatermark is not changed internally - the idea is that it gets set in a style's trigger section or alike. For example:

```xaml
<Style TargetType="{x:Type y:AutoCompleteBox}">
  <Style.Triggers>
    <Trigger Property="Text" Value="">
      <Setter Property="ShowWatermark" Value="True" />
    </Trigger>
  </Style.Triggers>
</Style>
```
Of course this could be part of the default style, I didn't think that far when I sent the pull request.

As for the WatermarkedTextBox: That's another dependency and possibly breaking change for the project (regarding styles implicitly targetting the TextBox in the ACB) versus 4 neutral changes (introduced 2 properties, added one entry to the template, another one as outlined above) to the existing control.
All that said, I began hacking these properties in because with the original 2010 release, popups refused to work correctly whenever I replaced the default control. But I still think it's worth it :)

**Comment by jogibear9988** [comment]
Maybe you can Add That Trigger To the Default Style?
But I also think we then don't need the ShowWatermark Property, we can directly hide the TemplatePart Showing the Watermark

**Comment by diab0l** [comment]
True.
Also, I think a read-only IsWatermarkVisible property and a WatermarkOpacity property would be good.
What do you think?

**Comment by jogibear9988** [comment]
Ok for me...

**Comment by diab0l** [comment]
Well, it's been a while, but I finally got around to implement some sane defaults.

Here's a breakdown of the changes:
- removed WatermarkShown property as outlined above
- added a trigger hiding the placeholder when the textbox is empty to the default style as outlined above
- added a DataTemplate/DataTemplateSelector pair for better styling support
- changed the name of the feature from watermark to placeholder which is more in-line with the HTML naming and logically correct with the behavior (one would expect a placeholder to disappear once the textbox is nonempty, but not a watermark).
- added a tab to the AutoCompleteBox samples to demonstrate the usage of the feature

What's still open is integrating the feature into the styles of the themes.

**Comment by diab0l** [comment]
You might want to revert the README.md
The change I made was meant for my local branch, but slipped into the PR

**Pull request merged**
