### PR TITLE
Migrate to sdk-based projects

### PR DESCRIPTION
**Pull request by ggeurts**

### CODE REVIEW

**Comment by jogibear9988** [comment]
should we increase major version?

**Comment by jogibear9988** [comment]
is this ready to merge?

**Comment by jogibear9988** [comment]
are you interested in joining dotnetprojects?

**Comment by jogibear9988** [comment]
think also we should remove nuspec and create the nuget directly via csproj.

**Comment by ggeurts** [comment]
This PR does not change the public API of the code, so a change in version number shouln't be required

**Comment by ggeurts** [comment]
Currently it's tricky to create a multi-assembly NuGet package with SDK builds

**Comment by ggeurts** [comment]
There is something to be said for packaging each assembly in its own NuGet package though, that's the direction where I will be heading for a private WpfToolkit build.

**Comment by jogibear9988** [comment]
you're right, I thought I switched to csproj packagein in wpfdesigner, but I still use nuspec: https://github.com/icsharpcode/WpfDesigner/blob/master/nuget/WpfDesigner.nuspec

**Comment by jogibear9988** [comment]
will you add the netstandard assemblys also to the nuspec?

**Comment by jogibear9988** [comment]
write me when it's ready to be merged

**Comment by jogibear9988** [comment]
and thanks for your help

**Comment by jogibear9988** [comment]
if you like we could switch to multiple nugets.

**Comment by ggeurts** [comment]
Ok, I will prepare the project for multiple NuGets, and let you know when merge is ok. Thank you!

**Comment by jogibear9988** [comment]
top.

**Comment by ggeurts** [comment]
@jogibear9988 This PR is read for merge as far as I am concerned.

**Comment by jogibear9988** [comment]
could you increase major, as this is now a breaking change

**Comment by jogibear9988** [comment]
@ggeurts sorry I haven't seen your comment

**Pull request merged**
